---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2
    ioapic: 'on'

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
    attributes:
      java:
        jdk_version: 7

suites:
  - name: mesosphere_slave
    run_list:
      - recipe[mesos::slave]
    attributes:
      mesos:
        type: mesosphere
        slave:
          master: test-master
